# Generated by Django 5.1.1 on 2025-02-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_text', models.TextField()),
                ('mon_text', models.TextField()),
                ('image', models.ImageField(upload_to='dare/')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Playertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=40)),
                ('mon_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Questionlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=40)),
                ('mon_name', models.CharField(max_length=40)),
                ('eng_desc', models.CharField(max_length=300)),
                ('mon_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=40)),
                ('mon_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_text', models.TextField()),
                ('mon_text', models.TextField()),
                ('image', models.ImageField(upload_to='question/')),
                ('playertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playertype')),
                ('questionlevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questionlevel')),
                ('questiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.questiontype')),
            ],
        ),
    ]
