# Generated by Django 5.1.1 on 2025-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dare/'),
        ),
    ]
