# Generated by Django 5.1.1 on 2025-02-26 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_dare_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dare',
            name='darelevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.questionlevel'),
            preserve_default=False,
        ),
    ]
