# Generated by Django 5.1.1 on 2025-04-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_dare_darelevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dare',
            old_name='darelevel',
            new_name='questionlevel',
        ),
        migrations.AddField(
            model_name='dare',
            name='playertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.playertype'),
            preserve_default=False,
        ),
    ]
