# Generated by Django 5.1.1 on 2025-04-24 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packname', models.CharField(max_length=30, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50, unique=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pack')),
            ],
        ),
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.PositiveIntegerField()),
                ('spies', models.PositiveIntegerField()),
                ('timer', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.appuser')),
            ],
        ),
    ]
