# Generated by Django 5.1.1 on 2025-04-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_appuser_created_at_pack_packitem_spy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='spy',
            name='created_at',
        ),
    ]
