# Generated by Django 5.1.1 on 2025-04-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_appuser_created_at_remove_spy_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packitem',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='spy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='PackItem',
        ),
        migrations.DeleteModel(
            name='Spy',
        ),
    ]
