# Generated by Django 5.1.1 on 2025-04-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_packitem_pack_remove_spy_user_delete_pack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packname', models.CharField(max_length=30, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50, unique=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.pack')),
            ],
        ),
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.PositiveIntegerField()),
                ('spies', models.PositiveIntegerField()),
                ('timer', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.appuser')),
            ],
        ),
    ]
