# Generated by Django 5.1.1 on 2025-04-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_pack_packitem_spy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='packname',
            new_name='engname',
        ),
        migrations.RenameField(
            model_name='packitem',
            old_name='itemname',
            new_name='itemengname',
        ),
        migrations.AddField(
            model_name='pack',
            name='monname',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packitem',
            name='itemmonname',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
