# Generated by Django 5.1.1 on 2025-04-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rename_packname_pack_engname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packitem',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='spy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='PackItem',
        ),
        migrations.DeleteModel(
            name='Spy',
        ),
    ]
