# Generated by Django 5.1.1 on 2025-04-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_packitem_pack_remove_spy_user_delete_pack_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
