# Generated by Django 5.2 on 2025-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qpay', 'QPay'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
    ]
