# Generated by Django 5.2 on 2025-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_order_alter_material_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
