# Generated by Django 5.2 on 2025-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('operator', 'Operator'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
