# Generated by Django 5.2 on 2025-05-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_customuser_phone_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.category'),
        ),
    ]
