# Generated by Django 5.1.3 on 2025-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
