name: frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0            # ✅ space after colon
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.16  # Keep only one version
  video_player: ^2.5.0
  lottie: ^3.0.0
  google_fonts: ^4.0.4    # ✅ space after colon
  audioplayers: ^6.4.0
  convex_bottom_bar: ^3.2.0
  flutter_animated_dialog: ^2.0.1
  shimmer: ^3.0.0
  flutter_image_compress: ^2.4.0 
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  just_audio: ^0.9.36
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bbb.jpg
    - assets/images.jpg
    - assets/momgol.jpg
    - assets/ami.jpg
    - assets/kind.jpg
    - assets/school.png
    - assets/9.jpg
    - assets/nemeh.webp
    - assets/audio/
    - assets/animals/
    - assets/animations/
  
   
