# Generated by Django 5.1.5 on 2025-05-07 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('grid_size', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GridData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid_data', to='word_search_api.level')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('english_words_guessed', models.IntegerField(default=0)),
                ('mongolian_words_guessed', models.IntegerField(default=0)),
                ('completed_levels', models.ManyToManyField(blank=True, to='word_search_api.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('EN', 'English'), ('MN', 'Mongolian')], max_length=2)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='word_search_api.level')),
            ],
        ),
    ]
