# Generated by Django 5.1.5 on 2025-02-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='careers',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommended_courses',
            field=models.ManyToManyField(to='app1.course'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommended_universities',
            field=models.ManyToManyField(to='app1.university'),
        ),
        migrations.AddField(
            model_name='university',
            name='courses',
            field=models.ManyToManyField(related_name='universities', to='app1.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app1.careerinsight'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.careerinsight'),
        ),
    ]
