# Generated by Django 5.1.5 on 2025-02-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_university_careers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='career_weight',
            field=models.JSONField(),
        ),
    ]
