# Generated by Django 5.1.5 on 2025-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_option_career_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerinsight',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
