# Generated by Django 5.1.5 on 2025-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_careerinsight_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerinsight',
            name='job_growth',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='option',
            name='career_weight',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='recommended_courses',
            field=models.ManyToManyField(blank=True, to='app1.course'),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='recommended_universities',
            field=models.ManyToManyField(blank=True, to='app1.university'),
        ),
    ]
