# Generated by Django 5.1.5 on 2025-03-14 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_careerinsight_job_growth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='application_url',
        ),
        migrations.RemoveField(
            model_name='university',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='university_images/'),
        ),
        migrations.CreateModel(
            name='UniversityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('careers', models.ManyToManyField(blank=True, to='app1.careerinsight')),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app1.university')),
            ],
        ),
    ]
