# Generated by Django 5.1.5 on 2025-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_news_newsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uniDetails_images/'),
        ),
    ]
