# Generated by Django 5.1.5 on 2025-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_universitydetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerinsight',
            name='avg_salary',
        ),
        migrations.RemoveField(
            model_name='careerinsight',
            name='job_growth',
        ),
        migrations.RemoveField(
            model_name='careerinsight',
            name='top_industries',
        ),
        migrations.AddField(
            model_name='careerinsight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='career_images/'),
        ),
        migrations.AddField(
            model_name='careerinsight',
            name='preparationTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CareerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_images/')),
                ('preparationTime', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('course', models.ManyToManyField(blank=True, to='app1.course')),
                ('university', models.ManyToManyField(blank=True, to='app1.university')),
            ],
        ),
    ]
