# Generated by Django 5.2 on 2025-04-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_careerinsight_avg_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdetails',
            name='name',
            field=models.CharField(default='Unknown Career', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='careerdetails',
            name='career',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app1.careerinsight'),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsdetails_images/'),
        ),
    ]
