# Generated by Django 5.2 on 2025-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_careerdetails_name_alter_careerdetails_career_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='career',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='recommended_courses',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='high_school_subjects',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='responses_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='suggested_career',
            field=models.CharField(default='Unknown Career', max_length=255),
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='recommended_universities',
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='recommended_universities',
            field=models.TextField(default='Unknown University'),
        ),
    ]
