# Generated by Django 5.1.6 on 2025-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='activity_media/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='answer_audios/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default='answer_images/default.jpg', null=True, upload_to='answer_images/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audios/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='lesson_images/default.jpg', upload_to='lesson_images/'),
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='image',
            field=models.ImageField(default='lesson_group_images/default.jpg', upload_to='lesson_group_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='question_audios/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='question_images/default.jpg', null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.ImageField(default='subject_icons/default.jpg', upload_to='subject_icons/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
