# Generated by Django 5.1.6 on 2025-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_activity_media_url_remove_answer_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='icon',
            field=models.ImageField(default='subject_icons/default.jpg', upload_to='subject_icons/'),
        ),
    ]
