# Generated by Django 5.1.6 on 2025-04-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_school_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='school_audios/'),
        ),
    ]
