# Generated by Django 5.1.6 on 2025-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_school_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='subjects_audios/'),
        ),
    ]
