# Generated by Django 5.1.6 on 2025-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subject_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessongroup',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_group_audios/'),
        ),
    ]
