# Generated by Django 5.1.6 on 2025-04-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lessongroup_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='animal_images/default.jpg', upload_to='animal_images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='animal_audios/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='api.subject')),
            ],
        ),
    ]
