# Generated by Django 5.1.6 on 2025-04-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_animaltype_animal_animal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
