# Generated by Django 5.1.6 on 2025-04-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='animal_videos/'),
        ),
    ]
