# Generated by Django 5.1.6 on 2025-04-22 06:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_base64',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='animal_videos/', validators=[api.models.validate_video]),
        ),
    ]
