# Generated by Django 5.1.6 on 2025-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userprofile_profile_picture_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
