# Generated by Django 5.1.6 on 2025-04-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_userprofile_profile_picture_base64_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
