# Generated by Django 5.1.6 on 2025-04-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_user_bio_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lesson',
        ),
    ]
