# Generated by Django 5.1.6 on 2025-04-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_activity_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='media',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.AddField(
            model_name='activity',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audios/'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.lessongroup'),
        ),
    ]
