# Generated by Django 5.1.6 on 2025-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_activity_media_remove_userprogress_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='animals',
            field=models.ManyToManyField(blank=True, related_name='activities', to='api.animal'),
        ),
    ]
