# Generated by Django 5.1.5 on 2025-03-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpart',
            old_name='image',
            new_name='Зураг',
        ),
        migrations.RenameField(
            model_name='carpart',
            old_name='name',
            new_name='Нэр',
        ),
        migrations.RenameField(
            model_name='carpart',
            old_name='created_at',
            new_name='Орсон_цаг',
        ),
        migrations.RenameField(
            model_name='carpart',
            old_name='description',
            new_name='Тайлбар',
        ),
        migrations.RenameField(
            model_name='carpart',
            old_name='category',
            new_name='Төрөл',
        ),
        migrations.RenameField(
            model_name='carpart',
            old_name='price',
            new_name='Үнэ',
        ),
        migrations.RemoveField(
            model_name='carpart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carpart',
            name='stock',
        ),
    ]
