# Generated by Django 5.1.5 on 2025-03-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_carpart_зураг_rename_name_carpart_нэр_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand'),
        ),
    ]
