# Generated by Django 5.2 on 2025-05-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_audio_lesson_image_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.category'),
        ),
    ]
