# Generated by Django 5.2 on 2025-05-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
