# Generated by Django 5.1.1 on 2025-04-24 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0002_alter_spy_players_alter_spy_spies_alter_spy_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy.appuser')),
            ],
        ),
    ]
