# Generated by Django 5.1.1 on 2025-04-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0004_remove_pack_monname_remove_packitem_itemmonname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='engname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='packitem',
            old_name='itemengname',
            new_name='itemname',
        ),
    ]
