# Generated by Django 5.1.1 on 2025-05-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0007_alter_appuser_options_alter_appuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
