# Generated by Django 5.1.1 on 2025-05-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0008_appuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='packitem',
            name='pack',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.DeleteModel(
            name='Spy',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
        migrations.DeleteModel(
            name='PackItem',
        ),
    ]
