# Generated by Django 5.1.1 on 2025-05-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0012_remove_appuser_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_at',
        ),
    ]
