# Generated by Django 5.1.1 on 2025-05-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0013_remove_appuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spy',
            name='pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spy.pack'),
            preserve_default=False,
        ),
    ]
