# Generated by Django 5.1.1 on 2025-05-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0014_spy_pack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spy',
        ),
    ]
