# Generated by Django 5.1.1 on 2025-05-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0016_spy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spy',
            name='pack',
        ),
        migrations.CreateModel(
            name='SpyPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isown', models.BooleanField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy.appuser')),
            ],
        ),
    ]
