# Generated by Django 5.1.1 on 2025-05-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0017_remove_spy_pack_spypack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
