# Generated by Django 5.1.1 on 2025-05-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0020_player_playername'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
