# Generated by Django 5.1.1 on 2025-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0022_remove_player_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='added',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
