# Generated by Django 5.1.1 on 2025-05-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spy', '0023_player_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='added',
        ),
    ]
